export const LOAD_VIDEOS = 'LOAD_VIDEOS';
export const LOAD_LATEST_VIDEO_SUCCESS = 'LOAD_LATEST_VIDEO_SUCCESS';
export const LOAD_LATEST_VIDEO_FAIL = 'LOAD_LATEST_VIDEO_FAIL';
export const LOAD_ONE_VIDEO_SUCCESS = 'LOAD_ONE_VIDEO_SUCCESS';
export const LOAD_ONE_VIDEO_FAIL = 'LOAD_ONE_VIDEO_FAIL';
export const LOAD_VIDEOS_SUCCESS = 'LOAD_VIDEOS_SUCCESS';
export const LOAD_VIDEOS_FAIL = 'LOAD_VIDEOS_FAIL';

export default {
    LOAD_VIDEOS,
    LOAD_VIDEOS_FAIL,
    LOAD_VIDEOS_SUCCESS,
    LOAD_LATEST_VIDEO_FAIL,
    LOAD_LATEST_VIDEO_SUCCESS,
    LOAD_ONE_VIDEO_SUCCESS,
    LOAD_ONE_VIDEO_FAIL
};
