export const LOAD_VIDEOS = 'LOAD_VIDEOS';
export const LOAD_VIDEOS_SUCCESS = 'LOAD_VIDEOS_SUCCESS';
export const LOAD_VIDEOS_FAIL = 'LOAD_VIDEOS_FAIL';

export default {
	LOAD_VIDEOS,
	LOAD_VIDEOS_FAIL,
	LOAD_VIDEOS_SUCCESS
}